version: '3.9'

services:
  ispconfig:
    image: ispconfigdocker:php74
    volumes:
      - type: volume
        source: eragondev_data
        target: /var/www
      - type: volume
        source: eragondev_db
        target: /var/lib/mysql
    container_name: eragondev
    hostname: dev
    domainname: mylocalenv.com
    cap_add: [
      SYS_ADMIN, LINUX_IMMUTABLE,
      # Pure-ftpd-mysql
      DAC_READ_SEARCH, SYS_NICE
    ]
    environment:
      - LANGUAGE=C
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - HOSTNAME=dev.mylocalenv.com            # see ./build/autoinstall.ini
      - HOSTNAME_EMAIL=mail.dev.mylocalenv.com # Hostname for email
      - DISABLED_SERVICES=rspamd unbound # disable services (apache2 clamav-daemon cron dovecot fail2ban mariadb postfix postfix pure-ftpd-mysql redis rspamd rsyslog spamassassin ssh unbound)
    ports: [
      # "53:53", # bind
      "110:110", # pop3
      "995:995", # pop3s
      "143:143", # imap
      "993:993", # imaps
      "25:25", # smtp
      "587:587", # smtps
      "3306:3306", # mysql
      "20-21:20-21", # pureftpd
      "80:80", "443:443", "8080:8080", # web
      "22:22", # sshd
      "30000-30009:30000-30009", # pure-ftpd
    ]
volumes:
  eragondev_data:
  eragondev_db:
